import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { DATA } from "@/data/resume";
import { ThemeProvider } from "@/components/theme-provider";
import { Nav } from "@/components/nav";
import { Footer } from "@/components/footer";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(DATA.url),
  title: {
    default: `${DATA.name} | Engineering Systems for Decision-Making`,
    template: `%s | ${DATA.name}`,
  },
  description: DATA.description,
  keywords: [
    "Priyanshu Gupta",
    "backend engineer",
    "distributed systems",
    "LLM agents",
    "Django",
    "Python",
    "RabbitMQ",
    "Celery",
  ],
  authors: [{ name: DATA.name, url: DATA.url }],
  creator: DATA.name,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: DATA.url,
    siteName: DATA.name,
    title: `${DATA.name} | Engineering Systems for Decision-Making`,
    description: DATA.description,
    // A real .png in public/, generated by scripts/generate-og.mjs. Next's
    // opengraph-image.tsx convention emits an extensionless file, which GitHub Pages
    // serves as application/octet-stream — social scrapers reject that.
    images: [{ url: "/og.png", width: 1200, height: 630, alt: DATA.name }],
  },
  twitter: {
    card: "summary_large_image",
    title: `${DATA.name} | Engineering Systems for Decision-Making`,
    description: DATA.description,
    images: ["/og.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  alternates: {
    canonical: "/",
    types: { "application/rss+xml": `${DATA.url}/rss.xml` },
  },
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-icon-180x180.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // suppressHydrationWarning is required by next-themes: it writes the theme class
    // onto <html> before React hydrates, which is by definition a server/client mismatch.
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <a
            href="#main"
            className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded focus:border focus:bg-background focus:px-3 focus:py-2 focus:text-sm"
          >
            Skip to content
          </a>
          {/*
            704px, giving a 656px text column.

            Picked by measuring, not taste. Line length is the real readability
            constraint (60-75 characters is the comfortable range) and it moves opposite
            to width, so a wider page reads worse while looking more generous. At 18px in
            Geist, 656px lands homepage prose around 78 characters and blog prose in the
            low 70s. 768px pushed the homepage to ~86; the old 672px-at-14px ran ~99,
            because small type hides how long lines already are.

            If you widen this, raise the font size with it or the lines get long again.
          */}
          <div className="mx-auto min-h-dvh w-full max-w-[44rem] px-6 py-12 sm:py-16">
            <Nav />
            <main id="main">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
